export interface LearnContent {
  id: string;
  slug: string;
  title: string;
  description: string;
  content: string;
  category: string;
  author: string;
  authorAvatar: string;
  date: string;
  readTime: number; // minutes
  difficulty: "beginner" | "intermediate" | "advanced";
  tags: string[];
  featured: boolean;
}

export const learnContent: LearnContent[] = [
  {
    id: "1",
    slug: "what-is-vibe-coding",
    title: "What Is Vibe Coding? The Complete Beginner's Guide",
    description: "Everything you need to know about vibe coding — what it is, how it works, why it matters, and how you can start building software today without traditional coding knowledge.",
    content: `
## What Is Vibe Coding?

Vibe coding is a new approach to software development where you describe what you want to build in natural language, and AI tools write the code for you. Instead of learning programming syntax and spending years mastering languages like JavaScript or Python, you communicate your ideas conversationally and iterate on the results.

The term was coined by Andrej Karpathy, former director of AI at Tesla, who described it as "fully giving in to the vibes" — trusting the AI to handle implementation details while you focus on the product vision.

## How It Works

1. **You describe what you want** — "Build a landing page with a hero section, feature grid, and email signup form"
2. **AI writes the code** — The tool generates production-quality code based on your description
3. **You review and iterate** — Look at the result, ask for changes, and refine
4. **You ship** — Deploy your creation to the web

## Who Is Vibe Coding For?

- **Entrepreneurs** who want to build MVPs without hiring developers
- **Designers** who want to bring their mockups to life
- **Product managers** who want to prototype ideas quickly
- **Students** learning to build software
- **Hobbyists** with app ideas they've never been able to build
- **Professional developers** who want to move 10x faster

## The Tools

The most popular vibe coding tools include:

- **Claude Code** — Anthropic's CLI tool for AI-assisted development
- **Cursor** — An AI-powered code editor
- **Bolt** — Browser-based AI app builder
- **Lovable** — AI tool focused on beautiful UI generation
- **Replit Agent** — AI-powered development in the browser

## Is It "Real" Programming?

Yes. The code generated by AI tools is real, production-quality code. The difference is in how it's created — through conversation rather than manual typing. The output is the same: working software that runs in browsers, on servers, and on phones.

## Getting Started

The fastest way to start is to install Claude Code and try building something small. Check out our [Getting Started guide](/guides/install-claude-code) for step-by-step instructions.
    `,
    category: "Fundamentals",
    author: "VibeCoded Team",
    authorAvatar: "/images/avatars/team.jpg",
    date: "2026-03-08",
    readTime: 8,
    difficulty: "beginner",
    tags: ["Introduction", "Beginner", "Vibe Coding"],
    featured: true,
  },
  {
    id: "2",
    slug: "choosing-the-right-ai-coding-tool",
    title: "Choosing the Right AI Coding Tool for Your Project",
    description: "A comprehensive comparison of the top AI coding tools — Claude Code, Cursor, Bolt, Lovable, and more. Find the right tool for your skill level and project type.",
    content: `
## The AI Coding Tool Landscape

The number of AI coding tools has exploded in 2025-2026. Each has different strengths, workflows, and ideal use cases. Here's how to choose.

## Claude Code (Terminal-Based)

**Best for**: Developers and power users who are comfortable in the terminal

**Strengths**:
- Full codebase understanding — reads and edits multiple files
- Runs commands, installs packages, manages git
- Works with any language, framework, or tool
- Most powerful for complex, multi-file projects

**Trade-offs**: Requires terminal comfort (though our guides can help!)

## Cursor (IDE-Based)

**Best for**: Developers who prefer a visual code editor

**Strengths**:
- Familiar VS Code interface with AI built in
- Inline code suggestions and chat
- Good for editing existing projects

**Trade-offs**: Less autonomous than Claude Code for multi-step tasks

## Bolt & Lovable (Browser-Based)

**Best for**: Complete beginners and quick prototypes

**Strengths**:
- No installation required
- Visual preview of changes in real-time
- Great for simple apps and landing pages

**Trade-offs**: Limited for complex projects, less control over the codebase

## How to Choose

| If you want... | Use this |
|---|---|
| Maximum power and flexibility | Claude Code |
| A familiar editor experience | Cursor |
| Zero setup, instant start | Bolt or Lovable |
| Mobile app development | Claude Code + Expo |
| Complex full-stack apps | Claude Code |

## Our Recommendation

Start with whatever feels least intimidating. You can always switch tools as your skills grow. The concepts transfer between tools — learning one makes the others easier.
    `,
    category: "Tools",
    author: "VibeCoded Team",
    authorAvatar: "/images/avatars/team.jpg",
    date: "2026-03-01",
    readTime: 12,
    difficulty: "beginner",
    tags: ["Tools", "Comparison", "Guide"],
    featured: true,
  },
  {
    id: "3",
    slug: "building-production-apps",
    title: "From Prototype to Production: Shipping Vibe-Coded Apps",
    description: "Your app works locally — now what? Learn how to take a vibe-coded project from prototype to production with databases, auth, payments, and deployment.",
    content: `
## The Gap Between Demo and Production

Building a working prototype with AI is surprisingly easy. Shipping a production app that real users depend on requires a few more considerations. This guide bridges that gap.

## Step 1: Add a Real Database

Local storage and JSON files work for demos, but production apps need a database.

**Recommended options**:
- **Supabase** — PostgreSQL with a generous free tier and built-in auth
- **PlanetScale** — Serverless MySQL, great for scaling
- **Neon** — Serverless PostgreSQL

Ask Claude Code: "Replace localStorage with Supabase. Set up the client, create the necessary tables, and migrate the existing data model."

## Step 2: Add Authentication

Most production apps need user accounts.

Ask Claude Code: "Add authentication using Supabase Auth. Include email/password signup, login, and a protected dashboard page. Add a user menu in the header showing the logged-in user's name."

## Step 3: Handle Errors Gracefully

Ask Claude Code: "Add error boundaries, loading states, and user-friendly error messages throughout the app. Show toast notifications for actions like saving, deleting, and errors."

## Step 4: Optimize for Performance

Ask Claude Code: "Analyze the app for performance issues. Add image optimization, lazy loading for below-the-fold content, and make sure the Lighthouse score is above 90."

## Step 5: Deploy

See our [Railway deployment guide](/guides/deploying-to-railway) for step-by-step instructions.

## Production Checklist

- [ ] Real database (not localStorage)
- [ ] Authentication
- [ ] Error handling
- [ ] Input validation
- [ ] Mobile responsive
- [ ] SEO meta tags
- [ ] Analytics
- [ ] Custom domain
- [ ] SSL certificate (usually automatic)
- [ ] Environment variables secured
    `,
    category: "Building",
    author: "VibeCoded Team",
    authorAvatar: "/images/avatars/team.jpg",
    date: "2026-02-22",
    readTime: 15,
    difficulty: "intermediate",
    tags: ["Production", "Deployment", "Best Practices"],
    featured: false,
  },
  {
    id: "4",
    slug: "design-principles-for-non-designers",
    title: "Design Principles for Non-Designers Building Apps",
    description: "You don't need a design degree to build beautiful apps. Learn the fundamental principles that make the difference between amateur and professional-looking software.",
    content: `
## Why Design Matters

Users judge your app in seconds. Good design builds trust and makes your app easier to use. The good news: a few simple principles get you 80% of the way there.

## Principle 1: Consistency

Use the same colors, fonts, spacing, and patterns everywhere. Pick a design system (like Tailwind CSS) and stick with it.

**Ask Claude**: "Use a consistent design system throughout the app. Primary color: indigo-600, spacing: multiples of 4px, border-radius: 8px for cards, 6px for buttons."

## Principle 2: Whitespace

More whitespace = more professional. Don't cram elements together.

**Ask Claude**: "Add more padding and spacing throughout the app. Use py-16 for sections, gap-6 for grids, and p-6 for cards."

## Principle 3: Typography Hierarchy

Use different sizes and weights to show what's important.

**Ask Claude**: "Set up a clear typography hierarchy — page titles at text-3xl font-bold, section headers at text-xl font-semibold, body text at text-base, and helper text at text-sm text-gray-500."

## Principle 4: Limit Your Palette

Use 2-3 colors maximum plus neutrals (grays).

## Principle 5: Align Everything

Elements that line up look intentional. Use grids.

## Quick Wins for Better-Looking Apps

1. Add subtle shadows to cards
2. Round your corners (8-12px)
3. Use a real font (Inter, Geist, or Plus Jakarta Sans)
4. Add hover effects on interactive elements
5. Use icons from a consistent set (Lucide, Heroicons)
6. Add smooth transitions (200ms ease)
    `,
    category: "Design",
    author: "VibeCoded Team",
    authorAvatar: "/images/avatars/team.jpg",
    date: "2026-02-15",
    readTime: 10,
    difficulty: "beginner",
    tags: ["Design", "UI/UX", "Beginner"],
    featured: false,
  },
  {
    id: "5",
    slug: "version-control-for-vibe-coders",
    title: "Git and Version Control for Vibe Coders",
    description: "Git might seem intimidating, but it's your safety net. Learn the essential commands that will save you when AI makes changes you don't want.",
    content: `
## Why Git Matters for Vibe Coding

When AI is writing your code, things can go wrong. Git lets you:
- Undo any change instantly
- See what changed and when
- Work on experiments without risking your main app
- Collaborate with others

## The 5 Git Commands You Actually Need

### 1. Save your work
\`\`\`bash
git add .
git commit -m "Add user login page"
\`\`\`

### 2. See what changed
\`\`\`bash
git status
git diff
\`\`\`

### 3. Undo the last AI change
\`\`\`bash
git checkout .  # Undo all uncommitted changes
\`\`\`

### 4. Create a safe experiment branch
\`\`\`bash
git checkout -b experiment/new-feature
# ... try stuff ...
git checkout main  # Go back if it didn't work
\`\`\`

### 5. Push to GitHub
\`\`\`bash
git push origin main
\`\`\`

## The Golden Rule

**Commit before every major Claude Code prompt.** This way, if something goes wrong, you can always go back.

## Pro Tip: Let Claude Handle Git

You can ask Claude Code to manage git for you:
- "Commit the current changes with a descriptive message"
- "Create a new branch called feature/dark-mode"
- "Show me what changed since the last commit"
    `,
    category: "Fundamentals",
    author: "VibeCoded Team",
    authorAvatar: "/images/avatars/team.jpg",
    date: "2026-02-08",
    readTime: 7,
    difficulty: "beginner",
    tags: ["Git", "Version Control", "Fundamentals"],
    featured: false,
  },
  {
    id: "6",
    slug: "ai-coding-best-practices",
    title: "10 Best Practices for AI-Assisted Development",
    description: "Battle-tested tips from experienced vibe coders on how to get the most out of AI coding tools while avoiding common pitfalls.",
    content: `
## 1. Start with a Clear Vision

Before opening any tool, write down:
- What problem does this solve?
- Who is the user?
- What are the 3-5 core features?

## 2. Build Incrementally

Don't try to build everything at once. Start with the smallest possible version that works, then add features one at a time.

## 3. Commit After Every Working State

Made a change that works? Commit it immediately. This is your checkpoint.

## 4. Review Every Change

AI can make mistakes. Read through the code changes, test the functionality, and verify it does what you asked.

## 5. Use Descriptive File Names

\`UserDashboard.tsx\` > \`page2.tsx\`
\`calculateShippingCost.ts\` > \`utils.ts\`

## 6. Keep Prompts Focused

One feature per prompt. Don't ask the AI to "add authentication, a dashboard, payments, and email notifications" all at once.

## 7. Test on Mobile

Over 50% of web traffic is mobile. Check your app on different screen sizes early and often.

## 8. Don't Reinvent the Wheel

Use existing libraries and services:
- Stripe for payments
- Supabase for database + auth
- Vercel/Railway for hosting
- Resend for emails

## 9. Security Basics

- Never commit API keys (use .env files)
- Validate user inputs
- Use HTTPS (automatic with most hosts)

## 10. Ship Imperfect, Iterate Fast

Your first version won't be perfect. Ship it, get feedback, improve.
    `,
    category: "Best Practices",
    author: "VibeCoded Team",
    authorAvatar: "/images/avatars/team.jpg",
    date: "2026-02-01",
    readTime: 9,
    difficulty: "intermediate",
    tags: ["Best Practices", "Tips", "Workflow"],
    featured: false,
  },
];

export const learnCategories = ["All", "Fundamentals", "Tools", "Building", "Design", "Best Practices"];
